development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://mvjhwhlvkjjtmr:kbujeipFecLGDN-Ww2jS1XlIZ3@ec2-54-243-245-58.compute-1.amazonaws.com:5432/d3emtrg7ej1i8a
