# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2699ec65853f8e5f8a3df90774d5e3fc24190c88a71726d6fa12a653f6adeeb61d404e8c345f2c36a17a8da75e367e8585840abcc65ac1fecff34c2c75412f2d

test:
  secret_key_base: 0b9c20baf2c871e346596e6116a1be3bcf19e18266b09226ade3ce700e0ef549ce33fff0ba4c319925c709dc167befc8e80488fff5750f7c667c5d678530bbbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
